### PR TITLE
Replace compile.exe with compile.bat

### PR DESCRIPTION
**Pull request by xPaw**
This removes 10 year old Deplhi thing, and replaces with a much smaller batch script.
However this means losing feature where compile.exe would check timestamps and not recompile plugins if they were not modified. Seeing as compile.sh doesn't have this feature either, I'm not sure if it's worth trying to implement it in batch.

This PR also brings compile.sh up to date.

### CODE REVIEW

**Comment by ClaudiuHKS** [comment]
Looks amazing. I am with you.
If possible, changing the icon of .bat file with favorite.ico would be great.

http://www.makeuseof.com/answers/change-icon-bat-file-windows-7/

**Comment by xPaw** [comment]
It's not possible to directly modify the icon, and I'm not going to ship a shortcut or bat-to-exe converter.

**Comment by Nextra** [comment]
Even though I wouldn't mind and the .sh doesn't provide it either, this is a step backwards in functionality. I'd prefer having the old functionality in the .bat and upgrading the .sh to do the same.

**Comment by Arkshine** [comment]
I would agree with Nextra too. It would make more sense this way.

**Comment by xPaw** [comment]
I've came up with the idea of checking timestamp of source file against compiled file, instead of storing it `compile.dat` file. However it's still rather hard to implement in batch.

**Comment by Nextra** [comment]
Yeah, batch is terrible for any kind of date manipulation. While the Delphi thing might not be pretty - it works. Having it around doesn't hurt anyone as it is maintenance free. Without a proper alternative we should not get rid of it.

**Comment by Freeman-AM** [comment]
However this means losing feature where compile.exe would check timestamps and not recompile plugins if they were not modified.

> -1 for me, just because of that.

**Comment by xPaw** [comment]
See my comment above about timestamps, I thought about adding a new parameter in amxxpc which would accomplish this.

**Comment by xkpx64** [comment]
Add some protection that make harder dissambly of .amxx.
This is major thing to do!

**Comment by Nextra** [comment]
Making .amxx harder to disassemble is the very very very very very very very very last thing on any priority list that anyone has ever thought of regarding AMXX. But thanks for the input.

**Pull request closed without merging**
