### PR TITLE
Add GeoIP data update to the automatic build system

### PR DESCRIPTION
**Pull request by Arkshine**
@psychonic It's based on your PR https://github.com/alliedmodders/sourcemod/pull/390 but I'm unsure of paths. Will it be fine?

### CODE REVIEW

**Comment by djearthquake** [comment]
_I need the raw long and lat for my work. Are there any plans to add it as a native please?_ Otherwise what are the maths to take the lon and lat for distance back to raw? When I tried to converse it the maths do not prove themselves. In fact I keep a log and see it's picking up Zeros in 1 case. When I go and check the IP it does have data.

So for the distance calculations it is flawed already. I had to go back to my raw data to see.

LOG
**Country: France, City: Prisse, Region: Bourgogne-Franche-Comte joined. |lat:214 lon:0|**

Is 0 correct? Why 4.6 please?
214/46 = 4.6

https://sciencing.com/convert-latitude-longtitude-feet-2724.html



mmdblookup --file GeoLite2-City.mmdb  --ip 109.25.197.97
        "latitude": 
          46.321300 <double>
        "longitude": 
          4.744700 <double>

**Comment by Nextra** [comment]
@djearthquake There are `Float:geoip_latitude(const ip[])` and `Float:geoip_longitude(const ip[])` defined in geoip.inc. Do you have an issue with these?

**Comment by djearthquake** [comment]
Those 2 natives do not proof back to raw coordinates as stated in my initial post. Can you show me the maths please if they do? How is "longitude":4.744700  zero?

**Comment by Nextra** [comment]
They do exactly what they are supposed to. You did something wrong in your code or you didn't install the GeoIP database correctly. Please ask for assistance in the [Scripting Help](https://forums.alliedmods.net/forumdisplay.php?f=11) section on our forums. Post more information about your setup and what you did, and provide your code so people can help you out.

**Comment by djearthquake** [comment]
amx_ctof and amx_ftoc. Is that a typo?


// native geoip_latitude(const ip[]);
static cell AMX_NATIVE_CALL amx_geoip_latitude(AMX *amx, cell *params)
{
	int length;
	char *ip = stripPort(MF_GetAmxString(amx, params[1], 0, &length));

	const char *path[] = { "location", "latitude", NULL };
	double latitude = lookupDouble(ip, path);

	return amx_ftoc(latitude);
}

// native geoip_longitude(const ip[]);
static cell AMX_NATIVE_CALL amx_geoip_longitude(AMX *amx, cell *params)
{
	int length;
	char *ip = stripPort(MF_GetAmxString(amx, params[1], 0, &length));

	const char *path[] = { "location", "longitude", NULL };
	double longitude = lookupDouble(ip, path);

	return amx_ftoc(longitude);
}

// native Float:geoip_distance(Float:lat1, Float:lon1, Float:lat2, Float:lon2, system = SYSTEM_METRIC);
static cell AMX_NATIVE_CALL amx_geoip_distance(AMX *amx, cell *params)
{
	float earthRadius = params[5] ? 3958.0 : 6370.997; // miles / km

	float lat1 = amx_ctof(params[1]) * (M_PI / 180);
	float lon1 = amx_ctof(params[2]) * (M_PI / 180);
	float lat2 = amx_ctof(params[3]) * (M_PI / 180);
	float lon2 = amx_ctof(params[4]) * (M_PI / 180);

	return amx_ftoc(earthRadius * acos(sin(lat1) * sin(lat2) + cos(lat1) * cos(lat2) * cos(lon2 - lon1)));
}

**Comment by Nextra** [comment]
This is not a place for support. Please post in the forums. The AMXX code works, I tested it.

**Comment by djearthquake** [comment]
What AMXX code works? What did you test exactly? If this is not the place for support then why am I bothering testing your work for you for free and offering solutions here on this site already? How do you think we got here? The auto packaging of GeoIP sent it to the general public in a unusable form. I sorted that? Remember? The arrogance of AMXX does not match the greatness. Really guys. Good bye. I just showed you the native was returning a 0 when bash shows there is data. There is not anything wrong with my database copy or my work. Yours buddy had the problem. How quickly you forget. Why this code roundup on the forums? Then get here with this unappreciative attitude like only 3 people can program C++ really? How clannish. This site is the source of that code it's C++ not Small Pawn Alliedmodders. You want me to broadcast this further? I shredded my databases that I could use bash and pull coordinates because you are so sure of yourself and guess what it did not do anything. It's time you take more of my advice and less of your own. Your forums are a bigot troll factory. Clean it up. Your code and packaging.

**Comment by Arkshine** [comment]
Helping is welcomed and appreciated, but please do it the proper way. 
Answering after a merged commit is not helpful and make difficult to track the discussion/problem.

If you have an issue, always go there: https://github.com/alliedmodders/amxmodx/issues. 
**It's important**. 

In your case, make sure you have the latest city database from Maxmind site (we know if there an issue with the current shipped database).

I tested your IP and it worked as expected:

```
L 03/13/2019 - 14:07:42: [test.amxx] lat = 46.321300
L 03/13/2019 - 14:07:42: [test.amxx] long = 4.744699
```

```SourcePawn
#include <amxmodx>
#include <geoip>

public plugin_init()
{
    new const ip[] = "109.25.197.97";

    new const Float:lat = geoip_latitude(ip);
    new const Float:long = geoip_longitude(ip);

    log_amx("lat = %f", lat);
    log_amx("long = %f", long);
}
```
Note: for debugging, you can dump your IP data directly in the console: `geoip dump <ip>`.

If you think there is a bug, **please create an issue instead**, elaborate as much as possible, and show your code as well.

**Pull request merged**
