### PR TITLE
Albanian Language translation support

### PR DESCRIPTION
**Pull request by CrXane**
This is a fully commitment of bringing Albanian language support to amxmodx.

Edit: 16 May 2019: All files have been fully translated. 
Collab with @lspublic

### CODE REVIEW

**Comment by S4pphire** [comment]
Note: pardon about my mistakes, I've never used GitHub before.

**Comment by Arkshine** [comment]
It's okay, don't worry. Thanks for contributing.

If I would suggest something the next time is to try to give meaningful commit name. You did one file per commit and it's a good thing, but you should have used commit name like "Update admin.txt" or "Add translations to admin.txt".

**Comment by lspublic** [comment]
> Note: pardon about my mistakes, I've never used GitHub before.

CrXane, can you edit some words in your translation i can tell you where is wrong ?

**Comment by CrXane** [comment]
For sure, I'll pack all the edits up and pull a new request including what Arkshine suggested.

**Comment by 4D1G06** [comment]
This is literally English to English translation! You used words that simply don't even exist in Albanian.

**Comment by CrXane** [comment]
There's no such translation to Albanian to specific words you may face into translations. The writing is based in the standart way of writing in Albanian. Currently I'm making a few edits here and there to come up with a final version.
There's tons of words that it's on Albanian language but are taken from English dictionary. By reading your comment, I can tell just by that you've never read a book.
 By the way send your translation you thought I poorly did, I mean who doesn't love judging, right?

**Comment by lspublic** [comment]
Adi jemi marr vesh me crxane ja kam dergu materialin edhe do ta poston perseri materialin e ri :) Easy boy

**Comment by 4D1G06** [comment]
You should simplify the translations, not everyone is able to identify or even understand some words from different dialect(s). So I suggest you to **review** what you did. I'm not complaining about your work at all, in fact it should be appreciated since for more than a decade none did so.

**Comment by WPMGPRoSToTeMa** [comment]
Is `ë` used in Albanian?

**Comment by 4D1G06** [comment]
Yes, both. I've tried before to output them in pawn, but got a 'e' instead . AFAIR.

**Comment by WPMGPRoSToTeMa** [comment]
@4D1G06 did you save the source file with `UTF-8 without BOM` encoding?

**Comment by 4D1G06** [comment]
That's probably like 3 years ago, I don't really remember what I got WHEN I tried different encoding.
I'll try in few minutes and give the results.

**Comment by CrXane** [comment]
I got some free time to re-edit some of the translation I did a few weeks ago. A round up of half the translation. Added missing 'ë' 'ç' as @WPMGPRoSToTeMa suggested. I'll update the remaining files the next week, I've been very busy as the final exams are comming.

**Comment by CrXane** [comment]
@Arkshine ^

**Comment by flamurimeri** [comment]
did this translation go to this version of amxmodx.. its totally fine and pure translated ! @Arkshine

**Comment by CrXane** [comment]
Not yet @flamurimeri
The commit needs comments from Albanians finding any mistakes there might be. It's common I would say.

**Comment by l3ndrit** [comment]
Good job mate

**Comment by CrXane** [comment]
_snap_

**Comment by Arkshine** [comment]
I can't reasonably check everything, but I shall trust you! Thanks.

**Pull request merged**
