### PR TITLE
Fix player transfering

### PR DESCRIPTION
**Pull request by shelru**

### CODE REVIEW

**Comment by Arkshine** [comment]
Could you provide some explanation for this, please?

**Comment by SmileYzn** [comment]
register_event also use enable_event and disable_event functions

**Comment by SmileYzn** [comment]
Probably it is because after admin change player team, he can back into old team??

**Comment by Freeman-AM** [comment]
It was already done @SmileYzn since my last commit on this plugin.
i bet the guy didn't even notice that the same offset is used with gamedata way few line after : 
set_ent_data(player, "CBasePlayer", "m_bTeamChanged", true);
It may completly block what he call fix depanding of conditions.
Anyway, I didn't read the whole plugin but double calling the same offset isn't the right way to do.
Plus it misses fakemeta checks.

**Comment by Arkshine** [comment]
It might be related to https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/client.cpp#L1933-L1941, from `HandleMenu_ChooseTeam`.

Basically, If you already died and changed teams once, the transfer will fail.

**Comment by shelru** [comment]
> Basically, If you already died and changed teams once, the transfer will fail.
Right.

Ok. Bye. But there an error. We must change m_bTeamChanged to false before change team, and remove `if (g_fakemeta)
				{
					set_ent_data(player, "CBasePlayer", "m_bTeamChanged", true);
				}`
Coz we don't need it.

**Comment by Arkshine** [comment]
Why did you close?

**Comment by shelru** [comment]
Coz im lazy;) And i can't find m_bHasChangeTeamThisRound in regamedll(strange).

**Comment by Arkshine** [comment]
As you can read above, `m_bHasChangeTeamThisRound ` is `m_bTeamChanged` ...

**Pull request closed without merging**
