### PR TITLE
Fix OnConfigsExecuted blocked with server_cmd("/maps") #728

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
It's just an example.
Fix it.

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/alliedmodders/amxmodx/issues/728

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine 
аркишин
проверяй.

**Comment by Freeman-AM** [comment]
You should name the PR "lol" or "cat ftw" or whatever pass in your mind...

**Comment by afwn90cj93201nixr2e1re** [comment]
PR name just for more attention.

**Comment by asherkin** [comment]
Please familiarise yourself with the [Contributing Guidelines](https://github.com/alliedmodders/amxmodx/blob/master/.github/CONTRIBUTING.md).

This PR can be re-opened if it is given a proper title and description, please don't open another.

**Comment by afwn90cj93201nixr2e1re** [comment]
@asherkin https://github.com/alliedmodders/amxmodx/pull/729#issuecomment-497755786 special for you.

**Comment by afwn90cj93201nixr2e1re** [comment]
@asherkin

**Comment by dvander** [comment]
It looks like this was never merged, and fixes a known issue - can we merge it?

**Comment by Arkshine** [comment]
Fix should be acceptable. It's indeed more reliable with the full path.

I can be wrong, but it's not a perfect fix. `MapConfigPath` is filled when `ExecuteAutoConfigs()` is executed. However, it's executed 6.1 seconds later. This means `strstr(command, MapConfigPath)` will match an empty string until filled and you could trigger likely the same issue with `server_cmd("")` -- but with should fix the issue with `/maps`.

**Comment by afwn90cj93201nixr2e1re** [comment]
It is really bad fix because as i said i did it to get an attention because the whole system where one of reserved path used only for amxmodx - is kinda dumb, so...
You need to think how to reorganize it. I would recommend you just to close eyes on it, because it is pretty useless and it will break something else, as i remember, probably that was the reason why i stopped forcing merging this PR into the master branch. Actually here's issue not only with '/maps' but with something else as well, again, as far as i remember.

**Comment by UnrealKaraulov** [comment]
https://github.com/alliedmodders/amxmodx/pull/1022

**Pull request closed without merging**
