### PR TITLE
Fixed value check in json_object_set_value

### PR DESCRIPTION
**Pull request by Th3-822**
Regression from #983

Code was only allowing json objects to be passed as arguments

### CODE REVIEW

**Comment by UnrealKaraulov** [comment]
@Th3-822 thanks! 

But why this pull request not merged?(

**Comment by UnrealKaraulov** [comment]
@dvander Please merge it, this is critical issue. I can't use this native because it really broken...

**Comment by Th3-822** [comment]
btw, it's in 1.9 too

**Comment by UnrealKaraulov** [comment]
@Th3-822 francoromaniello bad coder, this coder make broken code! ))))!!!! ))) 🤣 🤣 🤣

**Comment by UnrealKaraulov** [comment]
@Th3-822 in 1.9 it no has value check, and not broken

**Comment by Th3-822** [comment]
it is @ bb4b8182500cae1df02066eb32493debe73b3454

**Comment by UnrealKaraulov** [comment]
@Th3-822 yes, really.

**Comment by GoodbayKOD** [comment]
unknown-29

**Pull request merged**
