### PR TITLE
Add MPROP_SHOWPAGE

### PR DESCRIPTION
**Pull request by rsKliPPy**
Requested by Depresie: https://forums.alliedmods.net/showthread.php?t=303560

### CODE REVIEW

**Comment by Arkshine** [comment]
@rsKliPPy Looks like you need a little rebase for this one.

**Comment by rsKliPPy** [comment]
Done.

**Comment by PartialCloning** [comment]
Doesn't work. Incorrect usage of get_amxaddr? @rsKliPPy @Arkshine

**Comment by Arkshine** [comment]
Yes, I misses a `*`. It should be `*get_amxaddr`.

**Pull request merged**
