### PR TITLE
nvault.inc documentation fix

### PR DESCRIPTION
**Pull request by OciXCrom**
Almost all of the natives in this file are marked with `@noreturn` even though all of them have proper return values in different scenarios, especially the `nvault_get` function.

### CODE REVIEW

**Comment by Arkshine** [comment]
You don't need to explicit a `@return` when the only 'error' value is preceded with a runtime error. You will never use that return value.

**Comment by OciXCrom** [comment]
You're right. Should I remove those changes or let them be? The `nvault_get` and `nvault_prune` have proper return values that were missing.

**Comment by Arkshine** [comment]
Well, yes, you should keep only the relevant information and without the handle part.

**Comment by OciXCrom** [comment]
Done.

**Comment by Arkshine** [comment]
I guess it's okay. Thanks!

**Pull request merged**
