### PR TITLE
Changed wpindex to attackerindex

### PR DESCRIPTION
**Pull request by SmileYzn**
Changed wpindex to attackerindex, used the description as reference!

### CODE REVIEW

**Comment by rsKliPPy** [comment]
This is actually a breaking change, but I doubt anyone actually ever wrote `.wpnindex = value` while calling the function.

**Comment by SmileYzn** [comment]
The problem is usage of function istelf (documentation), i did not found anything that indicates the wpindex is client index in really. Only did a try error test.

Anyway someone have made a review of some descriptions in functions of csstats.inc that is a error in review.

in really, nothing to worry

**Comment by voed** [comment]
I think better just add comment to documentation that it's not a weapon index, but client index

**Comment by SmileYzn** [comment]
Someone can explain how this break the compatibility, or just give-me some documentation about it? Im back to amxx coding this week, and forgot some terms lol

**Comment by rsKliPPy** [comment]
If you had a function
`native func(param_a, param_b);`
you could call it as
`func(.param_a = 69, .param_b = 420)`

That's why changing parameter names is a breaking change.

**Comment by SmileYzn** [comment]
oh yes, i forgot about named params, thanks for explain

**Pull request closed without merging**
