### PR TITLE
Fix client_disconnected isn't called on mapchange when ReHLDS API ena…

### PR DESCRIPTION
**Pull request by WPMGPRoSToTeMa**
…bled

### CODE REVIEW

**Comment by Arkshine** [comment]
I guess it looks good. Too bad there are no enable/disable functions similar to cdetour so it would not be needed to rely on such global variables.

Thanks!

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine we need a class that will wrap detour and rehlds hook.

**Comment by kristi-alb** [comment]
wrong sorry

**Comment by Arkshine** [comment]
Should be fixed now, thanks to psychonic.

**Pull request merged**
