### PR TITLE
Fixed passing a temporary string to LIGHT_STYLE

### PR DESCRIPTION
**Pull request by WPMGPRoSToTeMa**

### CODE REVIEW

**Comment by Arkshine** [comment]
Related to https://github.com/alliedmodders/amxmodx/pull/250/commits/c531ad756d70338cc2bc8bb2952e37392eb187a4.
Reported by aron9forever on the forum: https://forums.alliedmods.net/showthread.php?t=301839.

**Comment by Arkshine** [comment]
Thanks!

**Comment by WPMGPRoSToTeMa** [comment]
> Related to c531ad7.

This buffer issue always was in `set_lights`, but it became observable in-game after c531ad7.

**Comment by justgo97** [comment]
what about `engfunc(EngFunc_LightStyle, 0, "z");` ?

**Comment by WPMGPRoSToTeMa** [comment]
@justgo97 it should be fixed too.

**Pull request merged**
