### PR TITLE
Add RequestFrame() native

### PR DESCRIPTION
**Pull request by rsKliPPy**
This makes it easy to offset execution to the next frame without manually hooking StartFrame or using other workarounds to do so.
```
/**
 * Creates a single use hook for the next frame.
 *
 * @param callback      Function to be executed on the next frame.
 * @param data          Optional data to be passed to the callback function.
 *
 * @note                Callback function prototype:
 *                          function(data)
 *
 * @noreturn
 */
native RequestFrame(const callback[], any:data = 0);
```

Note: It may be better to hook `void _Host_Frame(float time)` and execute frame hooks in there. Also possibly provide an easy way for other modules to hook that too in the future. I would like feedback on this matter.

Test plugin provided in *plugins/testsuite/request_frame_test.sma*.

### CODE REVIEW

**Comment by WPMGPRoSToTeMa** [comment]
Can you provide use-cases for this?

**Comment by rsKliPPy** [comment]
SourceMod had RequestFrame() native for a long time, so I thought why wouldn't we have it too.

Currently no useful examples on my mind.

**Comment by Arkshine** [comment]
I know plugins and I've also encountered such situations where you need to postpone at least the next frame to do stuffs. Especially true when you alter the game. I know some plugins which use the trick with `FM_StartFrame` (registering and unregistering in the hook) and also using `set_task`.

If we can have a readable, clean and precise way to do that, it's welcomed I guess.

**Comment by IgnacioFDM** [comment]
I've seen many plugins indeed using set_task for this purpose. I'd argue using set_task this way, FM_StartFrame or this new function is never the correct way, but sometimes it's "useful" when you are too lazy to investigate what the correct hook is.

**Comment by WPMGPRoSToTeMa** [comment]
I've remembered one situation where it can be used. You can use it for getting total money change after frame, like killing two players at once with awp.

**Pull request merged**
