### PR TITLE
Fix signed/unsigned mismatch warning

### PR DESCRIPTION
**Pull request by IgnacioFDM**

### CODE REVIEW

**Comment by Ni3znajomy** [comment]
These kind of warnings also occur in:
- https://github.com/alliedmodders/amxmodx/blob/master/modules/cstrike/cstrike/CstrikeItemsInfos.cpp#L106
- https://github.com/alliedmodders/amxmodx/blob/master/modules/cstrike/cstrike/CstrikeItemsInfos.cpp#L176
- https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/file.cpp#L604
- https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/CLang.cpp#L592

It'd be great if you could fix them all at once.

**Comment by IgnacioFDM** [comment]
Weird, is that with GCC? Because I don't get them with VC++

**Comment by Ni3znajomy** [comment]
Yes, GCC version 6.3.1

**Comment by IgnacioFDM** [comment]
Haven't compiled with GCC and I'm not sure if these fixes would be "correct", so please review the changes

**Comment by IgnacioFDM** [comment]
(forgot the file.cpp one)

**Comment by Ni3znajomy** [comment]
Compiles without warnings 👍

**Pull request merged**
