### PR TITLE
Hungarian lang update

### PR DESCRIPTION
**Pull request by regener**
- Resolves alliedmodders/amxmodx#652
- Eye candy language updates for Hungarian translation with the help of Norbee. @ ebateam

### CODE REVIEW

**Comment by WPMGPRoSToTeMa** [comment]
Can you move fixes for #652 to a new one PR?

**Comment by Arkshine** [comment]
Yes, WPMGPRoSToTeMa is right, @regener , you need to separate the issues for maintainability and visibility reasons.
Thanks for contributing!

**Comment by regener** [comment]
Actually I don't know how to remove that file from PR, I'm going to open new PRs...

**Comment by WPMGPRoSToTeMa** [comment]
You can now just add lang-related changes to this branch.

**Pull request closed without merging**
