### PR TITLE
Compiler: Increase the maximum number of array dimension

### PR DESCRIPTION
**Pull request by Arkshine**
Per request. SM uses 4D as well. To be discussed.

Increasing dimension is easy but a fix is necessarry and is stolen from SAMP guys: https://github.com/pawn-lang/compiler/commit/d14f4870a8069ca446c0528a39b75e7d081ba3d5 and https://github.com/pawn-lang/compiler/commit/1cca8af0d2c6d290c095f27f39bd941e4374054e

Small test plugin:
```SourcePawn
#include <amxmodx>

public plugin_init()
{
    new a[2][2][2][2] =
    {
        {
            {
                {1, 2}, {3, 4}
            },
            {
                {5, 6}, {7, 8}
            }
        },
        {
            {
                {11, 12}, {13, 14}
            },
            {
                {15, 16}, {17, 18}
            }
        }
    }

    for (new i = 0; i < sizeof a; i++)
    {
        for (new j = 0; j < sizeof a[]; j++)
         {
            for (new k = 0; k < sizeof a[][]; k++)
            {
                for (new l = 0; l < sizeof a[][][]; l++)
                {
                    server_print("a[%d][%d][%d][%d] = %d", i, j, k, l, a[i][j][k][l]);
                }
            }
        }
    }
}

Output:

a[0][0][0][0] = 1
a[0][0][0][1] = 2
a[0][0][1][0] = 3
a[0][0][1][1] = 4
a[0][1][0][0] = 5
a[0][1][0][1] = 6
a[0][1][1][0] = 7
a[0][1][1][1] = 8
a[1][0][0][0] = 11
a[1][0][0][1] = 12
a[1][0][1][0] = 13
a[1][0][1][1] = 14
a[1][1][0][0] = 15
a[1][1][0][1] = 16
a[1][1][1][0] = 17
a[1][1][1][1] = 18
```

Better visual diff for the fix:
image

Please give some test - here a temporay link for the lib (windows only): http://users.alliedmods.net/~arkshine/amxxpc32.dll

### CODE REVIEW

**Comment by justgo97** [comment]
What is the best use case for this feature ?

**Comment by ClaudiuHKS** [comment]
Sounds good to me as long as SM also has this.

**Comment by droads** [comment]
Concrete example of use for me:
`new g_assault_data[33][ASSAULT_NUM][10]
new g_lmg_data[33][LMG_NUM][10]
new g_shotgun_data[33][SHOTGUN_NUM][10]
new g_sniper_data[33][SNIP_NUM][10]
new g_smg_data[33][SMG_NUM][10]
new g_pp_data[33][PP_NUM][10]
new g_sec_data[33][SEC_NUM][10]
`
==>
`
#define WEAPON_TYPES 7
#define MAX_WEAPONS_IN_TYPE 10
new g_weapons_data[33][WEAPON_TYPES][MAX_WEAPONS_IN_TYPE][10]
`
A similar result can be achieved with a arrangement using 3 dimensional arrays.
This is example with arrangement
`
new g_weapons_data[33][WEAPONS_TYPES][1000]
data=g_weapon_data[iPlayer][WASSAULT][WEAPON_ID*DATASIZE_FOR_SINGLE_WEAPON+need_cell]
`
But this innovation will allow you to access data in more comfortably ways with using 'for', as example.
`
data=g_weapon_data[iPlayer][WASSAULT][WEAPON_ID][need_cell]
`

**Comment by WPMGPRoSToTeMa** [comment]
> more comfortably ways with using 'for'

What do you mean?

**Comment by droads** [comment]
> What do you mean?
Retrieving data from an array using with cycles, direct access to a cell.

**Comment by WPMGPRoSToTeMa** [comment]
@droads why does it need loops?

**Comment by droads** [comment]
> Why does it need loops?

This is an example, specifically in my case loop is needed to load information from MySql

**Comment by droads** [comment]
@Arkshine 
Unfortunately there was not enough time to full check on previous days.
And today i rewrited weapon unlock mechanics in mod and always work well!
Prior to this, all plugins were recompiled using a new compiler, no errors were noticed.
Functions like: set_array, get_array, arrayset etc works well..
No errors at this moment.

**Comment by Arkshine** [comment]
Thanks for testing!

**Pull request merged**
