### PR TITLE
Change MAX_PLAYERS value to 32

### PR DESCRIPTION
**Pull request by Arkshine**
It would seem that value set to `33` appears to be uncomfortable for people. 

Usually this define is always declared with `32` in plugins, because it's the technical limit, and a new player's array with `MAX_PLAYERS + 1`. There is nothing wrong doing `+ 1` and it explicits why we do that. Also, `32` can be used on others places, making the change a bit unwelcomed..

Let's revert to `32` which makes more sense in HL1/AMXX context.

### CODE REVIEW

**Comment by Arkshine** [comment]
@xPaw Is there anything else I could have forgotten? I'm pretty sure we have all now.

**Comment by xPaw** [comment]
Should be fine.

**Comment by Arkshine** [comment]
@Nextra , @xPaw said it should be fine. :bee:

**Comment by Nextra** [comment]
@xPaw has spoken. :sheep:

**Pull request merged**
