### PR TITLE
Plmenu: separation of cstrike version of base version

### PR DESCRIPTION
**Pull request by Freeman-AM**
This split is a requirement for further updates.

This update include:
- fakemeta module as a requirement rather than an optional module, because whatever we do in the future, we will need to work with offsets.
- move cstrike module as a requirement rather an option for cstrike/plmenu
- remove counter-strike related code in base/plmenu
- tell builder and installer about new files

### CODE REVIEW

**Comment by xPaw** [comment]
I would actually propose doing the opposite, merging mod-specific plugins into one, so they are easier to maintain.

**Comment by Arkshine** [comment]
If doing like current code, this is easier to split code for CS only. But if changed code is somehow abstracted so we have well defined block of specific mod-related code, I would not mind yes.

**Comment by Freeman-AM** [comment]
My plans have changed, it's a lot more in Work in Progress state now.
I'm working on something really different for base plugin.
It will be compatible with at least half-life half-life oppossing force and death match classic team system if enabled.

**Comment by Freeman-AM** [comment]
Working on this update paused until 15th June

**Comment by Freeman-AM** [comment]
Updated half-life version.
Comments would be appreciated.

**Comment by ClaudiuHKS** [comment]
Of course it would be better so all PlMenu plug-ins are merged together.
Easier to update, easier to maintain.

**Comment by Freeman-AM** [comment]
I'm closing this one. I don't work anymore on goldsource games.

**Pull request closed without merging**
