### PR TITLE
[WIP] New native client kick

### PR DESCRIPTION
**Pull request by wopox1337**
Added new native to AMXX Core: `client_kick(id, reason, ...);`

### CODE REVIEW

**Comment by WPMGPRoSToTeMa** [comment]
Do we really need formatting support here? We can just use `fmt`.

**Comment by wopox1337** [comment]
Forget about fmt(). Will be changed.

**Comment by wopox1337** [comment]
@WPMGPRoSToTeMa but.. What about how to call SV_DropClient?

**Comment by WPMGPRoSToTeMa** [comment]
@wopox1337 `SV_DropClient(player, false, "%s", reason)`?

**Comment by wopox1337** [comment]
closed via https://github.com/s1lentq/reapi/pull/135

**Pull request closed without merging**
