### PR TITLE
Update miscstats.sma

### PR DESCRIPTION
**Pull request by all85100**
Fixed display of your team name when the remaining enemy is displayed

### CODE REVIEW

**Comment by all85100** [comment]
error

**Comment by Soyrce** [comment]
error:
Error: Undefined symbol "MAX_PLAYERS" on line 60
Error: Invalid array size (negative or zero) on line 88

**Comment by Freeman-AM** [comment]
Excluding @Soyrce comment, who is reporting errors much more on his side such as outdated includes or some other fail on his side, there is effectively a bug concerning enemy remaining. But updating it this way isn't the way to do i believe. Cause this part is not clear at all, at the first time you read it. A more complete rewrite should be done. I will see what can i do in another PR.

**Comment by regener** [comment]
Could be closed I think, it is fixed since last commits.
https://github.com/alliedmodders/amxmodx/commits/master/plugins/cstrike/miscstats.sma

**Pull request closed without merging**
