### PR TITLE
Port bugfix for incorrect heap deallocation on conditional operator

### LINKED ISSUE #621: Runtime error when using the conditional operator with fmt
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/amxmodx/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version: Windows 10 64 Bits
  * Game/AppID (with version if applicable): Half-Life 7561
  * Current AMX Mod X version: 1.8.3 5169
  * Current Metamod version: v1.21p37
# Description
I'm trying to show an empty message in case some condition becomes false, the best think that came to my mind to improve readability is to use the ternary operator, but it shows me a runtime error...

# Problematic Code (or Steps to Reproduce)
Put this code in plugin_init, compile and test it
  ```PAWN
	server_print(id, "%s", true ? fmt("Hello") : "");
  ```

# Logs
[AMXX] Run time error 8: heap low

### PR DESCRIPTION
**Pull request by WPMGPRoSToTeMa**
Fixes #621.

There are another changes in `hier13`, but I've ported only fix.
I'm a bit worry that this fix doesn't save `ALT` register, maybe it is guaranteed that `ALT` isn't used across condition and branch body?

@rtxa test [it](https://github.com/alliedmodders/amxmodx/files/2474778/amxxpc32.zip) please.

Related to #623.

### CODE REVIEW

**Comment by Arkshine** [comment]
I tried a little.

It works well for general use like:

```SourcePawn
server_print("1. %s", test1 ? fmt("Something") : ""); // Nothing
server_print("2. %s", test2 ? fmt("Something") : ""); // "Something"
server_print("3. %s", test1 ? "" : fmt("Something")); // "Something"
server_print("4. %s", test2 ? "" : fmt("Something")); // Nothing
server_print("5. %s", test1 ? "Hello" : "World");     // Hello
server_print("6. %s", test2 ? "Hello" : "World");     // World
server_print("7. %s", test2 ? (test2 ? "Egg" : "Something") : "Something else"); // Egg
server_print("8. %s", test2 ? (test1 ? "Egg" : "Something") : "Something else"); // Something
server_print("9. %s", test1 ? (test2 ? "Egg" : "Something") : "Something else"); // Something else
```

However, it asserts (line1085) with the following:
```SourcePawn
server_print("10. %s", test2 ? (test2 ? fmt("Egg") : "Something") : "Something else"); // Egg
server_print("11. %s", test2 ? (test1 ? fmt("Egg") : "Something") : "Something else"); // Something
```
Note that without the assert, the first works fine, but the second throwns a runtime error.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine can you test your code with #623?

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine can you try to test it on SP compiler and somehow on upstream compiler?

**Comment by WPMGPRoSToTeMa** [comment]
Tested it on the upstream compiler and it is also bugged: http://tpcg.io/7OMWqr.

**Comment by Arkshine** [comment]
I tried it, but I see no difference. Still throw an assert, and even without, still see runtime error.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine did you compile it yourself? Or downloaded from the first post?

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine sorry, I tested it only on 1.8.1. Now it should work.

**Comment by Arkshine** [comment]
Well, still the same. I have even tried to copy-paste manually hier13() from the PR.

**Comment by Arkshine** [comment]
I see, actually it works, but not with a function retourning an array.

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine that is because this function is located under it call. On the first pass it doesn't know what this function actually returns.

**Comment by Arkshine** [comment]
Without assertion, it seems to work fine. 
It's working under 1.8.2, It's stills a regression and something should be done.
Maybe the assertion could be commented?

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine unfortunately it generates a bad assembly, try:
```Pawn
server_print("42. %s", true ? "Something" : fmt("Egg"));
```

**Comment by WPMGPRoSToTeMa** [comment]
It is bugged in SourcePawn too:
```SourcePawn
#include <sourcemod>

#pragma semicolon 1
//#pragma newdecls required

public Plugin myinfo = {
	name        = "",
	author      = "",
	description = "",
	version     = "0.0.0",
	url         = ""
};

public void OnPluginStart()
{
	PrintToServer(true ? "Hello, World!" : fmt2());
}

fmt2() {
	new arr[256];
	return arr;
}
```
There is no heap "free":
```Assembly
 0xB68       PROC                        ; OnPluginStart
 0xB6C       BREAK     
 0xB70       BREAK     
 0xB74       CONST.pri               0x1
 0xB7C       JZER              jump_0000
 0xB84       CONST.pri             0x8DC
 0xB8C       JUMP              jump_0001
 0xB94       HEAP                  0x400 ; target:jump_0000
 0xB9C       PUSH.alt  
 0xBA0       PUSH.C                  0x0
 0xBA8       CALL             .3028.fmt2
 0xBB0       POP.pri   
 0xBB4       SM_TRACKER.PUSH.C            0x400
 0xBBC       PUSH.pri   ; target:jump_0001
 0xBC0       SYSREQ.N      PrintToServer (1 args)
 0xBCC       ZERO.pri  
 0xBD0       RETN      
```

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine try it.

**Comment by Arkshine** [comment]
Looks like it doesn't throw an assert anymore. At runtime, it looks fine as well.

**Comment by Arkshine** [comment]
@WPMGPRoSToTeMa Do you think it's needed to add more conditions for the reparsing?

**Comment by WPMGPRoSToTeMa** [comment]
@Arkshine I think it isn't worth to add them.

**Comment by Arkshine** [comment]
Alright, let's merge in master first and see if people have issues.

**Pull request merged**
