### PR TITLE
Hungarian language update

### PR DESCRIPTION
**Pull request by regener**
Eye candy language updates for Hungarian translation with the help of Norbee. @ ebateam

(Sorry again for my messing with PRs)

### CODE REVIEW

**Comment by regener** [comment]
Why does it add it to the same PR when I sent a new one wit ha different name?
I give up lol.

**Comment by WPMGPRoSToTeMa** [comment]
You should create another branch for the new PR, but you can also just use online github editor to submit a PR for typo fixes in build script.

**Comment by Arkshine** [comment]
Are you done with the update or do you plan more? I'm saying that because only 13 files among 29 are concerned.

**Comment by regener** [comment]
We did changes to get rid of bad affix uses that could happen in the affected plugins and fixed some typos, yet I think we are done for now (until new paragraphs come with new features or anything).

Meanwhile that pull bot crashed everything now, because I have deleted and reforked this project yesterday and the advanced settings file is missing... I can't find the Revert button from smatphone even on desktop view, so if I get home around 11 hours later I will revert that from desktop app.

Sorry for the delay.

**Comment by regener** [comment]
This will be last time I use this cr*p desktop app, it reverted the stuff that pull bot has done, but also added the old metamod text...

**Pull request closed without merging**
