### PR TITLE
Fix gcc 9.2 compilation.

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes: #806

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine wake up dude.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also we should add 
`Wno-unknown-warning-option` for old compilers, but im not sure when exactly it was added.

**Comment by Ecklory** [comment]
@Arkshine 
On 9.x, the build works, on 8.x i don't check.

**Comment by Ecklory** [comment]
@Arkshine 
Аркаша, чё такой кислый?

**Comment by ShootingKing-AM** [comment]
Why this PR still a draft ?
There is a problem with AMBuildScript on newer versions of gcc/g++, which failes the build, and the proposed changes fixes the problem.
My versions,
```
g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

**Pull request merged**
