### PR TITLE
Merge 1.9.0 fixes to 1.10 branch

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
So, maybe now it's should automerge.

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine any ideas?

**Comment by afwn90cj93201nixr2e1re** [comment]
изображение
xD

**Comment by Arkshine** [comment]
That's not something you should be able to. `master` branch contains already all those commits.
I think the PR about AL translations kind of fucked up things and GitHub lost its mind.

For the record, the author created one branch per commit (likely he used directly GitHub interface) and this leads to:

**Comment by afwn90cj93201nixr2e1re** [comment]
xD

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine r u sure?
Or github rly fucked up.

изображение
What 'bout this one?
изображение

**Comment by afwn90cj93201nixr2e1re** [comment]
Can we fix 1.9/1.10 branch for not confusing on `34 commits ahead`?

**Comment by Arkshine** [comment]
I believe there is nothing to do. 
Those are likely commits which have been cherry-picked from `master` (typically only bug-fixes/doc/translations since `1.9` is in _beta_, which should be released soon and we don't want to introduce more stuff.)

**Comment by afwn90cj93201nixr2e1re** [comment]
So, we should just remember that the 1.9 branch 34 commit's same already merged, xD.
So, maybe we should accept fixes only in 1.10 branch? And merge manually to 1.9 instead accept to 1.9 and merge to 1.10?
This is better than using old src's to build amxmodx.

**Comment by afwn90cj93201nixr2e1re** [comment]
And @Arkshine could you implement some api's for meta plugin's(amxx modules) for loading plugins?
Some forward's which called on plugin load and some native for directly plugin loading from some modules?
Now i should rebuild amxmodx and make change there https://github.com/alliedmodders/amxmodx/blob/9bcabfeb1f774439475313c30fb3fe256870268f/amxmodx/meta_api.cpp#L490
and write my code for custom condition plugin's loading.

Is there anyway to implement it in separate module?

**Comment by Arkshine** [comment]
I think you misunderstand something. 
* `master` is the development branch. You work always on `master`.
* `1.9` branch was created based off  `master` at some point. This the next stable version, and because it's a major version since a long time, this needs to be tested and we don't want to introduce more features, only fixes. You want to keep this branch stable.

This means, currently:
* Any new features merged in `master` is kept in `master`. 
* Any bug-fixes/translations/documentation updates merged in `master` is reflected to `1.9` branch as well (when I don't forget it).

There are auto-generated builds for both branches.
---

About your other question, that's not the proper place. Please use the forum, or eventually create a new issue.

**Comment by afwn90cj93201nixr2e1re** [comment]
> I think you misunderstand something.
No, i know how it's work.

So, can u just answer is g_plugins external for modules?)

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine so, i found it. Seem's like it's `g_fn_LoadAmxScriptEx`, how i can use it in amxmodx module?
Can you create simple example or faq on forum?

**Pull request closed without merging**
