### PR TITLE
Implement plugins loading order (alphabetic)

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Fixes: #876

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine, @dvander 

Core, enchachment labels and merge it asap...

**Comment by afwn90cj93201nixr2e1re** [comment]
изображение

**Comment by dvander** [comment]
Relying on file names to enforce ordering is not a good idea. It is better to write plugins that are resilient to load order.

**Comment by afwn90cj93201nixr2e1re** [comment]
Em, what r u talking about? And then why we need maps/plugins-mapname.ini lists? Why we need plugins- prefixes at all then?

**Comment by dvander** [comment]
You shouldn't rely on plugin load order. SourceMod loads all *.smx files it sees and does not guarantee load order.

I've been away from AMX Mod X long enough that I shouldn't be making this decision, though, so I leave the review to @Arkshine and others.

**Comment by afwn90cj93201nixr2e1re** [comment]
I know how sourcemod works, it's sometimes designed more better than amxmodx, that's cause why we need order in plugins-* loading.

**Comment by afwn90cj93201nixr2e1re** [comment]
And also we can make some metamodule, if this pr not gonna be accepted, but imo it's should be implemented in core tho.

**Comment by afwn90cj93201nixr2e1re** [comment]
I just made amxmodx module.

**Pull request closed without merging**
