### PR TITLE
add levenshtein distance

### PR DESCRIPTION
**Pull request by alldroll**
The games are place where developer has deal with natural language. It would be nice to have tools for processing it. In this PR was implemented algorithm `Levenshtein distance`
 with memory usage `O(min(n, m)`) and time complexy `O(mn)`. 
There is list of tools which i am going to implement (If natural language processing tools are welcomed):
* `Soundex`
* `Metaphone`
* Improve Levenshtein distance (`Damerau–Levenshtein distance`)
* `Prefix tree (trie)`

### CODE REVIEW

**Comment by rsKliPPy** [comment]
The usage of these algorithms is very specific and, in my opinion, they are well out of AMXX's scope.

What you could do is implement that in Pawn and post it in Code Snippets/Tutorials on the forum, or if you really prefer to do it in C++, possibly using some libraries for these algorithms to make it easier for you, implement it in a module and post it on the forums. I'm sure someone will make use of it.

**Comment by IgnacioFDM** [comment]
I think this could be a nice feature

Imagine the following

```amx_kick arksihne```

```Did you mean "amx_kick Arkshine"? ```
```Type "amx_kick %" to confirm```

```amx_kick %```
```Arkshine was kicked from the server```

**Comment by rsKliPPy** [comment]
Maybe if we had a better target filter (see #368 ) so it works on all commands, but just as a native on its own I don't think it currently has place in AMXX. If a PR extends all AMXX commands to use this new feature, then probably yes.

**Comment by alldroll** [comment]
We can use this tools for detecting swear words. But @rsKliPPy is right, this should be a module or plugin.

**Pull request closed without merging**
