### PR TITLE
.del

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
@Arkshine why not?

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
How we must keep 1.10 actual?

**Comment by afwn90cj93201nixr2e1re** [comment]
So, seem's like problem is only that' no albanian translation in 1.10. Im gonna fix it. Wait.

**Comment by Arkshine** [comment]
`master` branch is the latest of everything.
`1.9` branch is the next release and is currently accepting only bug-fixes. 

Usually, when someone does a PR on `master` and it's beneficial to add it to `1.9` branch, I need to manually cherry-pick that commit. Sometimes, I forget to add it, so feel free to remind it if it's the case.

**Comment by afwn90cj93201nixr2e1re** [comment]
5 min pls.

**Pull request closed without merging**
