### PR TITLE
Fix uncolor print

### PR DESCRIPTION
**Pull request by 9iky6**
Add 0 byte default color (yelow) to show color message.

### CODE REVIEW

**Comment by Nextra** [comment]
Your code overwrites plugin data instead of actually inserting the 0x01, this is a bug.

**Comment by 9iky6** [comment]
Unfortunately I don't know how to do differently, but in *.the sma plug-ins necessary to use this option, and nothing terrible happens (no data replacement). (sorry for the translator)

**Comment by Nextra** [comment]
That is because they then have the format function write from msg[1] onwards, keeping the msg[0] intact. We'll think about how to solve this, thanks for the suggestion.

**Comment by Arkshine** [comment]
Thanks. I've reposted in #338.

@9iky6 You should really use a tool like SmartGIT, so you can work locally and amending/merging commits easily.

**Pull request closed without merging**
