### PR TITLE
Overhaul Restrict Weapons plugin - part 1

### PR DESCRIPTION
**Pull request by Arkshine**
Requires ~~#342~~,  ~~#344~~.

Essentially:
- Used new stuffs to simplify things and for better performance overall
- Removed menu/command listing pagination by organizing items per weapon class
- Moved hardcoded message/define to ML/cvar
- Minor improvements here and there (consistency, check, visual, etc.)

Some details are available in commit.

More features could be added in another PR.

### CODE REVIEW

**Comment by GoRiLliAz** [comment]
:monkey:

Works well, no bug

I would improve the description by including that the  weaprest_de_dust.ini file file is created automatically via the menu.

**Comment by Arkshine** [comment]
I've tested again the plugin. This should be enough good for now.

@Nextra, @rsKliPPy 

Possible features to be considered in another PR:
- Per-team restriction
- Individual restriction (?)
- Touch restriction (on the ground, given directly)
- An option to wait for the next round if any changes are made from command/menu.
- Improving the menu in order to restrict all items or a group of items (?)

**Comment by Arkshine** [comment]
@rsKliPPy @IgnacioFDM  @Ni3znajomy @Nextra Can someone do some fast review please?

**Comment by rsKliPPy** [comment]
> Possible features to be considered in another PR:
Make it so if per-map setting is met it can also be read from `configs/maps/weapres_mapname.init` to remove clutter in the `configs` folder.

However, it's ready. :ship:

**Pull request merged**
