### PR TITLE
allow arrayset to accept any type

### PR DESCRIPTION
**Pull request by justgo97**
example of use case : 
```
#include <amxmodx>

new Float:g_FloatArray[33]

public plugin_init( )
{
    register_plugin( "arrayset", "0.0.1", "JustGo" )

    for( new i = 1; i <= 32; i++ )
    {
        g_FloatArray[i] = random_float(1.0, 9.0)
        server_print( "g_FloatArray[%d]=%f", i, g_FloatArray[i] )
    }

    register_concmd( "amx_arrayset", "cmd_arrayset")
}

public cmd_arrayset( )
{
    arrayset( g_FloatArray, 0.0, sizeof(g_FloatArray) )

    for( new i = 1; i <= 32; i++ )
    {
        server_print( "g_FloatArray[%d]=%f", i, g_FloatArray[i] )
    }
}
```

### CODE REVIEW

**Comment by voed** [comment]
Its gonna break a tag, isn't it?

**Comment by WPMGPRoSToTeMa** [comment]
@voed what do you mean?

**Comment by voed** [comment]
@WPMGPRoSToTeMa  i mean SomeTag:somearray[] after arrayset will be any:somearray[], or not?🤔

**Comment by rsKliPPy** [comment]
That's not how it works.

**Comment by justgo97** [comment]
@voed the **any:** tag means it can accept any type, in the past **arrayset** will give you a tag mismatch with **Float**, **Bool**...ect and now that will not happen

**Comment by voed** [comment]
Ok, nvm

**Comment by Arkshine** [comment]
Should be fine.

**Comment by AdamRichard21st** [comment]
Sorry about posting in a merged request, but, I got a short question about arraysets.
How about making it possible to arrayset multidimensional arrays?

**Pull request merged**
