### PR TITLE
Change AMX Mod X Lang Files Hash Method

### PR DESCRIPTION
**Pull request by ClaudiuHKS**
Change AMX Mod X Language Files hashing method from MD5 to CRC32 because it is 2x or even 3x faster and more reliable for that type of hash. Not for security, but for comparing files' content difference.

### CODE REVIEW

**Comment by xPaw** [comment]
What about replacing `FileList`/`CRC32Pair` with a `HashMap` from AMTL, I think that would be better.

**Comment by ClaudiuHKS** [comment]
Yes, it will be a good idea, but I need now to get rid of that "MySQLThreadingFix" commit made on this PR by mistake.

**Comment by xPaw** [comment]
If you are going to work more on this, it would be worth looking into using AMTL for other lookup tables as well (for `LookUpVec`, `m_LookUpTable` and some others).

**Comment by Nextra** [comment]
This whole mechanism should be redone as it isn't working properly and is mostly pointless, so this is just a band-aid fix that doesn't tackle the underlying problem. You should expand the scope of your changes (feel free to contact me for details) or close the PR if you don't want to do so. Judging from what I see surrounding this whole stuff I wouldn't feel comfortable merging this short-sighted improvement.

**Comment by ClaudiuHKS** [comment]
Of course I will do some updates in here as Arkshine and xPaw recommended.
But, I don't get Nextra's message.

"You should expand the scope of your changes (feel free to ask around for details) or close the PR if you don't want to do so."

How can I expand the scope of my changes?

**Comment by Nextra** [comment]
What I mean by that is that the PR is currently focused on changing the hash function for language files. I don't think this is a good change, as the whole hashing mechanism is currently broken and arguably pointless. If you wanted to change anything about this particular section of code you should *expand the scope of this PR* to include much more than just changing the hash function.

**Comment by ClaudiuHKS** [comment]
Exactly. Because this Pull Request was not mergeable due to a branch problem, it is going to be now closed. A new Pull Request is now opened, that recommends not using Language Files hashing anymore, but a more efficient method, .st_mtime comparison.

Also, some unused code will be removed in the opened Pull Request.

**Pull request closed without merging**
