### PR TITLE
Fix MySQL connector link

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
that's strange little bit.

**Comment by afwn90cj93201nixr2e1re** [comment]
fucking piece of shit.

**Comment by afwn90cj93201nixr2e1re** [comment]
idk

**Comment by afwn90cj93201nixr2e1re** [comment]
mysqlclient.lib(net_serv.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in basic_sql.obj

**Comment by Arkshine** [comment]
There is a reason why 6.1.1 is used. If I remember, the next versions, XP/2003 support is dropped and static lib are provided instead.

https://web.archive.org/web/20160825184854/http://dev.mysql.com/doc/relnotes/connector-c/en/news-6-1-2.html

**Comment by afwn90cj93201nixr2e1re** [comment]
Yep, btw there is problem, no archive... I just updated link and everything .... fuck.

**Comment by afwn90cj93201nixr2e1re** [comment]
oh, thanks... im gonna fix it now, hah

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine ready.

**Comment by Arkshine** [comment]
Thanks.

**Comment by afwn90cj93201nixr2e1re** [comment]
Can  you also merge non-breakable changes too? like adding menu_setaccess native and etc.

**Comment by afwn90cj93201nixr2e1re** [comment]
new gcc compiler flags and other stuff like that

**Pull request merged**
