### PR TITLE
Fixed some natives descriptions

### PR DESCRIPTION
**Pull request by voed**

### CODE REVIEW

**Comment by Arkshine** [comment]
Thanks!

**Comment by Nextra** [comment]
The copy pasta is strong with this one. Good spot :)

**Comment by voed** [comment]
Also, documentation needs update: http://www.amxmodx.org/api/amxmodx/is_linux_server
pawn-docgen does not removing exist data from database, as i know

**Comment by Nextra** [comment]
Parser needs to be run manually I think.

**Pull request merged**
