### PR TITLE
Albania Language - Version 1.9.0.5241

### PR DESCRIPTION
**Pull request by lspublic**
Hello all i add Albania Lang in all file in data/lang

### CODE REVIEW

**Comment by eat1k** [comment]
You have only updated mapsmenu.txt file, could you make translations for other files?

**Comment by lspublic** [comment]
> You have only updated mapsmenu.txt file, could you make translations for other files?

Yes i translate all file in data/lang because i set and for plugins and i like to add in official version

**Comment by Phantomism** [comment]
Here's some translations I've done a few years ago. Some of them might not be translated good but I did my best. It needs an update for sure.
[AMX Mod X - Albanian Translation.zip](https://github.com/alliedmodders/amxmodx/files/3076243/AMX.Mod.X.-.Albanian.Translation.zip)

**Comment by Arkshine** [comment]
Duplicate of #698.

**Pull request closed without merging**
