### PR TITLE
Fix menu crashes

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
sometimes dropclient and other stuff which was merged into amxmodx not called, and check's 
`if(!pPlayer->ingame)` not working properly, so, we should return everything to clientdrop and remove deprecation from client_disconnect, coz disconnected is really piece of shit.

**Comment by afwn90cj93201nixr2e1re** [comment]
i really don't wanna explain why this bug caused by replacing default meta disconnect with dropclient and other stuff like this, coz it's gonna takes too much and i should explain too much stuff about it, btw u free to investigate it.

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine

**Comment by afwn90cj93201nixr2e1re** [comment]
"in show_menu(tagAMX*,"
and
"in menu_display(tagAMX*,"
to google.

u should reopen this #645 and close with this pr.

**Comment by afwn90cj93201nixr2e1re** [comment]
@Arkshine

**Comment by Arkshine** [comment]
Thanks for the help.

However, if you want to be taken seriously, may I suggest:
* Do not spam – there is an edit button
* Mind your language & stop bashing – this is not helpful
* Explain properly – people are not clairvoyant and this won't help the review process

Thanks for your understanding.

Note: If you want to talk about a specific feature, please open an issue and start the discussion from there respectfully.

**Comment by afwn90cj93201nixr2e1re** [comment]
did u?
изображение


i think no.

**Comment by afwn90cj93201nixr2e1re** [comment]
изображение



изображение



also i wanna say that that is not clear solution, we should return to using meta client disconnect and reset stuff directly in them instead new way.

**Comment by voed** [comment]
Newmenus already fixed in #671. Old-style already has ingame check.

**Comment by afwn90cj93201nixr2e1re** [comment]
Не связаны.

**Comment by voed** [comment]
Then we need to fix `ingame` value because there should be much more unsafe code if ingame behavior is broken

**Comment by afwn90cj93201nixr2e1re** [comment]
> sometimes dropclient and other stuff which was merged into amxmodx not called, and check's
if(!pPlayer->ingame) not working properly, so, we should return everything to clientdrop and remove deprecation from client_disconnect, coz disconnected is really piece of shit.

> this bug caused by replacing default meta disconnect with dropclient and other stuff like this

> we should return to using meta client disconnect and reset stuff directly in them instead new way

 > Then we need to fix ingame value because there should be much more unsafe code if ingame behavior is broken

@Arkshine

**Comment by etojuice** [comment]
Is this problem really cstrike-exclusive?

**Comment by afwn90cj93201nixr2e1re** [comment]
rehlds exclusive.
dropclient exclusive.

**Comment by etojuice** [comment]
> 
> 
> rehlds exclusive.
> dropclient exclusive.

Then you should perform the check outside `if (g_bmod_cstrike)` condition, right?

**Comment by afwn90cj93201nixr2e1re** [comment]
Жуйс. Это псевдофикс. Нет, не за пределами, все это должно было изначально хэндлится ingame check'ом, но из-за этой хрени с dropclient'ом, которая описана 20 раз выше that's ingame check doesn't work as expected.

Why we should check is pdata valid out of scope pdata using? Idk.

**Comment by afwn90cj93201nixr2e1re** [comment]
I don't think that u should merge this fix.
I wanna say that u should remove deprecation from client_disconnect and return reset stuff to client_disconnect.


u can also ask tema for that.

**Comment by WPMGPRoSToTeMa** [comment]
Basically I don't understand what this bug is about. Can you write a single comment with explanations and examples?

**Comment by Arkshine** [comment]
Not sure from where you did this screenshot. It's not even the current code:

image

https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/meta_api.cpp#L906-L935 or did I miss something?

**Comment by Arkshine** [comment]
The check on this PR makes sense, but same as WPMGPRoSToTeMa, I really don't understand what you're saying just above.

This is the original code in this callback. It still does the same thing.

image

Or do I miss something?

**Comment by afwn90cj93201nixr2e1re** [comment]
i dont think that this is exactly same.

@WPMGPRoSToTeMa  should investigate when disconnect not called, coz sometimes also is_user_connected check's doesnt work properly. But if i downgrading to 1.8.2 or 1.8.3 they r work's as expected, there is also too much topics with rehlds + latest amxmodx with that stuff, that's really strange.
My mission is end, i just write something about it to get attention.

**Comment by afwn90cj93201nixr2e1re** [comment]
Continue discussion in https://github.com/alliedmodders/amxmodx/pull/264#issuecomment-658530597, coz seems like i found some problems.

**Pull request closed without merging**
